
for /f %%x in ('powershell Get-Date -Format "yyyyMMdd-HHmmss"') do set "mensajeback=backend-%%x"
for /f %%x in ('powershell Get-Date -Format "yyyyMMdd-HHmmss"') do set "mensajefrontweb=frontweb-%%x"
for /f %%x in ('powershell Get-Date -Format "yyyyMMdd-HHmmss"') do set "mensajefrontmobile=frontmobile-%%x"
for /f %%x in ('powershell Get-Date -Format "yyyyMMdd-HHmmss"') do set "mensajeelbueno=elbueno-%%x"
for /f %%x in ('powershell Get-Date -Format "yyyyMMdd-HHmmss"') do set "mensajeapirest=apirest-%%x"
for /f %%x in ('powershell Get-Date -Format "yyyyMMdd-HHmmss"') do set "mensajeproy4=proy4-%%x"
for /f %%x in ('powershell Get-Date -Format "yyyyMMdd-HHmmss"') do set "mensajeclasetypescr=clasetypescr-%%x"
for /f %%x in ('powershell Get-Date -Format "yyyyMMdd-HHmmss"') do set "mensajeawesomeTSProje=AwesomeTSProje-%%x"

start cmd.exe /k "cd C:\Users\nicolas\Desktop\BACKNODE\BackendTrabajo & git add . & git commit -m %mensajeback% & git push origin master" 
start cmd.exe /k "cd C:\Users\nicolas\Desktop\BACKNODE\FrontWebAsistencia & git add . & git commit -m %mensajefrontweb% & git push origin main" 
start cmd.exe /k "cd C:\Users\nicolas\Desktop\BACKNODE\FrontCelular & git add . & git commit -m %mensajefrontmobile% & git push origin main" 
start cmd.exe /k "cd C:\Users\nicolas\Desktop\BACKNODE\elbueno & git add . & git commit -m %mensajeelbueno% & git push origin main" 
start cmd.exe /k "cd C:\Users\nicolas\Desktop\BACKNODE\apirestsocial & git add . & git commit -m %mensajeapirest% & git push origin main" 
start cmd.exe /k "cd C:\Users\nicolas\Desktop\BACKNODE\17-proyecto4 & git add . & git commit -m %mensajeproy4% & git push origin main" 
:: start cmd.exe /k "cd C:\Users\nicolas\Desktop\TypeScript\clase-typescript & git add . & git commit -m %mensajeclasetypescr% & git push origin main" 
start cmd.exe /k "cd C:\Users\nicolas\Desktop\TypeScript\AwesomeTSProject & git add . & git commit -m %mensajeawesomeTSProje% & git push origin main" 